data_dir: /data-net/storage/datasets/

debug: true

# Train
train: true
batch_size: 2
gradient_accumulation_steps: 8
max_steps: 100000
save_steps: 10000

# Optimizer and Scheduler
lr: 0.0002
lr_scheduler_type: constant_with_warmup # constant_with_warmup, linear, cosine
warmup_ratio: 0.1

# Eval
eval: false

# Saving
only_keep_best: true
save_dir: save
project_name: DocT5
save_answers: false


# Example:
# accelerate launch --multi-gpu --num_processes=2 train.py -m save/DocT5-ocr-base -d SP-DocVQA --config-path configs/train.yml --num_gpus 2