data_dir: /gpfs/scratch/ehpc44/datasets/

debug: true

# Train
batch_size: 2
gradient_accumulation_steps: 8
max_steps: 10000
save_steps: 1000

# Optimizer and Scheduler
lr: 0.0002
lr_scheduler_type: constant_with_warmup # constant_with_warmup, linear, cosine
warmup_ratio: 0.1

# Eval
eval: true
eval_batch_size: 2
eval_start: false
eval_accumulation_steps: 100

# Saving
only_keep_best: true
save_dir: /gpfs/projects/ehpc44/DocT5/save
project_name: DocT5
save_answers: false


# Example:
# accelerate launch --multi-gpu --num_processes=4 train.py -m save/DocT5-ocr-base -d SP-DocVQA --config-path configs/train_eval.yml --num_gpus 4