data_dir: /gpfs/scratch/ehpc44/datasets/

debug: true

# Train
train: true
batch_size: 2
gradient_accumulation_steps: 2
max_steps: 25000
save_steps: 5000
mixed_precision: 'bf16'

# Optimizer and Scheduler
lr: 0.0002
lr_scheduler_type: constant_with_warmup # constant_with_warmup, linear, cosine
warmup_ratio: 0.1

# Eval
eval: false

# Saving
only_keep_best: true
save_dir: /gpfs/projects/ehpc44/DocT5/save
project_name: DocT5
save_answers: false


# Example:
# sbatch run.slurm train.py -m save/DocT5-ocr-base -d OCR-IDL -bs 8 --config-path configs/train.yml --wandb