data_dir: /gpfs/scratch/ehpc44/datasets/

debug: true

# Train
train: true
batch_size: 4
gradient_accumulation_steps: 2
max_steps: 10000
save_steps: 1000
mixed_precision: 'bf16'


# Optimizer and Scheduler
lr: 0.0002
lr_scheduler_type: constant_with_warmup # constant_with_warmup, linear, cosine
warmup_ratio: 0.1

# Eval
eval: true
eval_batch_size: 4
eval_start: false
best_metric: 'ANLS'
eval_accumulation_steps: 100

# Saving
only_keep_best: true
save_dir: /gpfs/projects/ehpc44/DocT5/save
project_name: DocT5
save_answers: false


# Example: sbatch run.slurm train.py -m model -d SP-DocVQA -bs 4 --save_steps 500 --max_steps 2000  --config-path configs/train_eval.yml --wandb
